### ISSUE TITLE
Loading a Set File that already has Tags jumbles all the Tags with the wrong events.

### ISSUE THREAD

**Issue by Theendeavorer** [VisLab/HEDTools#5]
When loading a Set File that already contains tags, all the tags are added to the wrong events. I was not yet able to establish if it is just an issue after adding Event\Label and Event\Description to the files, or if it also occurs with just Attribute\ added to the files. I will add a comment when I can verify this.

**Comment by jcockfie** [comment]
This is a issue. This is going to be fixed by allowing the user to specify the ordering of the fields (most important to least important). The tags found in the most important field will be associated with this field. The tags found in the next important field will be associated with this field, and so forth.

**Comment by jcockfie** [comment]
This is not an issue
